using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace D3BitGUI
{
    public class StatTriplet
    {
        public string EquipmentType { get; set; }
        public string StatName { get; set; }
        public double StatValue { get; set; }

        public StatTriplet(string equipmentType, string statName, double statValue)
        {
            EquipmentType = equipmentType;
            StatName = statName;
            StatValue = statValue;
        }
    }

    public static class Data
    {
        public static Dictionary<string, double> starWeights = new Dictionary<string, double>
                                                     {
                                                         {"pick", 2},
                                                         {"mvspd", 2},
                                                         {"atkspd", 2},
                                                         {"gf", 2},
                                                         {"mf", 2},
                                                         {"loh", 3.4},
                                                         {"life%", 2},
                                                         {"ar", 3.2},
                                                         {"crit", 3.4},
                                                         {"critd", 3.4},
                                                         {"block", 2},
                                                         {"soc", 1.4}
                                                     };

        public static List<StatTriplet> MaxStats = new List<StatTriplet>
                                                       {
                                                            new StatTriplet("Weapon", "Dex", 350),
                                                            new StatTriplet("Weapon", "Int", 350),
                                                            new StatTriplet("Weapon", "Str", 350),
                                                            new StatTriplet("Weapon", "Vit", 350),
                                                            new StatTriplet("Off-Hand", "Dex", 178),
                                                            new StatTriplet("Off-Hand", "Int", 178),
                                                            new StatTriplet("Off-Hand", "Str", 178),
                                                            new StatTriplet("Off-Hand", "Vit", 178),
                                                            new StatTriplet("Shield", "Dex", 200),
                                                            new StatTriplet("Shield", "Int", 200),
                                                            new StatTriplet("Shield", "Str", 200),
                                                            new StatTriplet("Shield", "Vit", 200),
                                                            new StatTriplet("Ring", "Dex", 178),
                                                            new StatTriplet("Ring", "Int", 178),
                                                            new StatTriplet("Ring", "Str", 178),
                                                            new StatTriplet("Ring", "Vit", 178),
                                                            new StatTriplet("Amulet", "Dex", 302),
                                                            new StatTriplet("Amulet", "Int", 302),
                                                            new StatTriplet("Amulet", "Str", 302),
                                                            new StatTriplet("Amulet", "Vit", 302),
                                                            new StatTriplet("Shoulders", "Dex", 200),
                                                            new StatTriplet("Shoulders", "Int", 200),
                                                            new StatTriplet("Shoulders", "Str", 300),
                                                            new StatTriplet("Shoulders", "Vit", 200),
                                                            new StatTriplet("Helm", "Dex", 200),
                                                            new StatTriplet("Helm", "Int", 300),
                                                            new StatTriplet("Helm", "Str", 200),
                                                            new StatTriplet("Helm", "Vit", 200),
                                                            new StatTriplet("Pants", "Dex", 200),
                                                            new StatTriplet("Pants", "Int", 200),
                                                            new StatTriplet("Pants", "Str", 200),
                                                            new StatTriplet("Pants", "Vit", 300),
                                                            new StatTriplet("Gloves", "Dex", 300),
                                                            new StatTriplet("Gloves", "Int", 300),
                                                            new StatTriplet("Gloves", "Str", 200),
                                                            new StatTriplet("Gloves", "Vit", 200),
                                                            new StatTriplet("Chest Armor", "Dex", 200),
                                                            new StatTriplet("Chest Armor", "Int", 200),
                                                            new StatTriplet("Chest Armor", "Str", 200),
                                                            new StatTriplet("Chest Armor", "Vit", 300),
                                                            new StatTriplet("Bracers", "Dex", 200),
                                                            new StatTriplet("Bracers", "Int", 200),
                                                            new StatTriplet("Bracers", "Str", 200),
                                                            new StatTriplet("Bracers", "Vit", 200),
                                                            new StatTriplet("Boots", "Dex", 300),
                                                            new StatTriplet("Boots", "Int", 200),
                                                            new StatTriplet("Boots", "Str", 200),
                                                            new StatTriplet("Boots", "Vit", 200),
                                                            new StatTriplet("Belt", "Dex", 200),
                                                            new StatTriplet("Belt", "Int", 200),
                                                            new StatTriplet("Belt", "Str", 300),
                                                            new StatTriplet("Belt", "Vit", 200),
                                                            new StatTriplet("Cloak", "Dex", 178),
                                                            new StatTriplet("Cloak", "Int", 178),
                                                            new StatTriplet("Cloak", "Str", 178),
                                                            new StatTriplet("Cloak", "Vit", 258),
                                                            new StatTriplet("Mighty Belt", "Dex", 178),
                                                            new StatTriplet("Mighty Belt", "Int", 178),
                                                            new StatTriplet("Mighty Belt", "Str", 258),
                                                            new StatTriplet("Mighty Belt", "Vit", 178),
                                                            new StatTriplet("Spirit Stone", "Dex", 178),
                                                            new StatTriplet("Spirit Stone", "Int", 258),
                                                            new StatTriplet("Spirit Stone", "Str", 178),
                                                            new StatTriplet("Spirit Stone", "Vit", 178),
                                                            new StatTriplet("Voodoo Mask", "Dex", 178),
                                                            new StatTriplet("Voodoo Mask", "Int", 258),
                                                            new StatTriplet("Voodoo Mask", "Str", 178),
                                                            new StatTriplet("Voodoo Mask", "Vit", 178),
                                                            new StatTriplet("Wizard Hat", "Dex", 178),
                                                            new StatTriplet("Wizard Hat", "Int", 258),
                                                            new StatTriplet("Wizard Hat", "Str", 178),
                                                            new StatTriplet("Wizard Hat", "Vit", 178),
                                                            new StatTriplet("Weapon", "LoK", 2878),
                                                            new StatTriplet("Weapon", "LoH", 959),
                                                            new StatTriplet("Weapon", "LPS", 64),
                                                            new StatTriplet("Weapon", "LS", 3),
                                                            new StatTriplet("Off-Hand", "GlobeHP", 5977),
                                                            new StatTriplet("Off-Hand", "LRegen", 234),
                                                            new StatTriplet("Off-Hand", "Life%", 9),
                                                            new StatTriplet("Shield", "GlobeHP", 12794),
                                                            new StatTriplet("Shield", "LRegen", 342),
                                                            new StatTriplet("Shield", "Life%", 16),
                                                            new StatTriplet("Ring", "GlobeHP", 5977),
                                                            new StatTriplet("Ring", "LRegen", 234),
                                                            new StatTriplet("Ring", "LoK", 985),
                                                            new StatTriplet("Ring", "LoH", 328),
                                                            new StatTriplet("Ring", "Life%", 9),
                                                            new StatTriplet("Amulet", "GlobeHP", 5977),
                                                            new StatTriplet("Amulet", "LRegen", 410),
                                                            new StatTriplet("Amulet", "LoK", 1971),
                                                            new StatTriplet("Amulet", "LoH", 657),
                                                            new StatTriplet("Amulet", "Life%", 14),
                                                            new StatTriplet("Shoulders", "GlobeHP", 12794),
                                                            new StatTriplet("Shoulders", "LRegen", 342),
                                                            new StatTriplet("Shoulders", "Life%", 12),
                                                            new StatTriplet("Helm", "GlobeHP", 12794),
                                                            new StatTriplet("Helm", "LRegen", 342),
                                                            new StatTriplet("Helm", "Life%", 12),
                                                            new StatTriplet("Pants", "GlobeHP", 12794),
                                                            new StatTriplet("Pants", "LRegen", 342),
                                                            new StatTriplet("Gloves", "GlobeHP", 12794),
                                                            new StatTriplet("Gloves", "LRegen", 342),
                                                            new StatTriplet("Chest Armor", "GlobeHP", 12794),
                                                            new StatTriplet("Chest Armor", "LRegen", 599),
                                                            new StatTriplet("Chest Armor", "Life%", 12),
                                                            new StatTriplet("Bracers", "GlobeHP", 12794),
                                                            new StatTriplet("Bracers", "LRegen", 342),
                                                            new StatTriplet("Boots", "GlobeHP", 12794),
                                                            new StatTriplet("Boots", "LRegen", 342),
                                                            new StatTriplet("Belt", "GlobeHP", 12794),
                                                            new StatTriplet("Belt", "LRegen", 342),
                                                            new StatTriplet("Belt", "Life%", 12),
                                                            new StatTriplet("Cloak", "GlobeHP", 5977),
                                                            new StatTriplet("Cloak", "LRegen", 410),
                                                            new StatTriplet("Cloak", "Life%", 9),
                                                            new StatTriplet("Mighty Belt", "GlobeHP", 5977),
                                                            new StatTriplet("Mighty Belt", "LRegen", 234),
                                                            new StatTriplet("Mighty Belt", "LS", 3),
                                                            new StatTriplet("Mighty Belt", "Life%", 9),
                                                            new StatTriplet("Spirit Stone", "GlobeHP", 5977),
                                                            new StatTriplet("Spirit Stone", "LRegen", 234),
                                                            new StatTriplet("Spirit Stone", "LPS", 30),
                                                            new StatTriplet("Spirit Stone", "Life%", 9),
                                                            new StatTriplet("Voodoo Mask", "GlobeHP", 5977),
                                                            new StatTriplet("Voodoo Mask", "LRegen", 234),
                                                            new StatTriplet("Voodoo Mask", "Life%", 9),
                                                            new StatTriplet("Wizard Hat", "GlobeHP", 5977),
                                                            new StatTriplet("Wizard Hat", "LRegen", 234),
                                                            new StatTriplet("Wizard Hat", "Life%", 9),
                                                            new StatTriplet("Weapon", "Exp", 24),
                                                            new StatTriplet("Weapon", "LvlRe", 18),
                                                            new StatTriplet("Weapon", "Soc", 1),
                                                            new StatTriplet("Off-Hand", "MF", 18),
                                                            new StatTriplet("Off-Hand", "GF", 20),
                                                            new StatTriplet("Off-Hand", "Exp", 24),
                                                            new StatTriplet("Off-Hand", "Soc", 1),
                                                            new StatTriplet("Shield", "MF", 20),
                                                            new StatTriplet("Shield", "GF", 25),
                                                            new StatTriplet("Shield", "Exp", 24),
                                                            new StatTriplet("Shield", "Soc", 1),
                                                            new StatTriplet("Ring", "MF", 18),
                                                            new StatTriplet("Ring", "GF", 20),
                                                            new StatTriplet("Ring", "Exp", 22),
                                                            new StatTriplet("Ring", "Soc", 1),
                                                            new StatTriplet("Amulet", "MF", 40),
                                                            new StatTriplet("Amulet", "GF", 40),
                                                            new StatTriplet("Amulet", "Exp", 24),
                                                            new StatTriplet("Amulet", "Soc", 1),
                                                            new StatTriplet("Shoulders", "MF", 20),
                                                            new StatTriplet("Shoulders", "GF", 25),
                                                            new StatTriplet("Shoulders", "Exp", 24),
                                                            new StatTriplet("Shoulders", "Pick", 7),
                                                            new StatTriplet("Shoulders", "LvlRe", 18),
                                                            new StatTriplet("Helm", "MF", 20),
                                                            new StatTriplet("Helm", "GF", 25),
                                                            new StatTriplet("Helm", "Exp", 24),
                                                            new StatTriplet("Helm", "Pick", 7),
                                                            new StatTriplet("Helm", "LvlRe", 18),
                                                            new StatTriplet("Helm", "Soc", 1),
                                                            new StatTriplet("Pants", "MF", 20),
                                                            new StatTriplet("Pants", "GF", 25),
                                                            new StatTriplet("Pants", "Exp", 24),
                                                            new StatTriplet("Pants", "Pick", 7),
                                                            new StatTriplet("Pants", "LvlRe", 18),
                                                            new StatTriplet("Pants", "Soc", 2),
                                                            new StatTriplet("Gloves", "MF", 20),
                                                            new StatTriplet("Gloves", "GF", 25),
                                                            new StatTriplet("Gloves", "Exp", 24),
                                                            new StatTriplet("Gloves", "Pick", 7),
                                                            new StatTriplet("Gloves", "LvlRe", 18),
                                                            new StatTriplet("Chest Armor", "MF", 20),
                                                            new StatTriplet("Chest Armor", "GF", 25),
                                                            new StatTriplet("Chest Armor", "Exp", 24),
                                                            new StatTriplet("Chest Armor", "Pick", 7),
                                                            new StatTriplet("Chest Armor", "LvlRe", 18),
                                                            new StatTriplet("Chest Armor", "Soc", 3),
                                                            new StatTriplet("Bracers", "MF", 20),
                                                            new StatTriplet("Bracers", "GF", 25),
                                                            new StatTriplet("Bracers", "Exp", 24),
                                                            new StatTriplet("Bracers", "Pick", 7),
                                                            new StatTriplet("Bracers", "LvlRe", 18),
                                                            new StatTriplet("Boots", "MF", 20),
                                                            new StatTriplet("Boots", "GF", 25),
                                                            new StatTriplet("Boots", "Exp", 24),
                                                            new StatTriplet("Boots", "MvSpd", 12),
                                                            new StatTriplet("Boots", "Pick", 7),
                                                            new StatTriplet("Boots", "LvlRe", 18),
                                                            new StatTriplet("Belt", "MF", 20),
                                                            new StatTriplet("Belt", "GF", 25),
                                                            new StatTriplet("Belt", "Exp", 24),
                                                            new StatTriplet("Belt", "Pick", 7),
                                                            new StatTriplet("Belt", "LvlRe", 18),
                                                            new StatTriplet("Cloak", "MF", 18),
                                                            new StatTriplet("Cloak", "GF", 20),
                                                            new StatTriplet("Cloak", "Exp", 24),
                                                            new StatTriplet("Cloak", "Pick", 7),
                                                            new StatTriplet("Cloak", "LvlRe", 16),
                                                            new StatTriplet("Cloak", "Soc", 3),
                                                            new StatTriplet("Mighty Belt", "MF", 18),
                                                            new StatTriplet("Mighty Belt", "GF", 20),
                                                            new StatTriplet("Mighty Belt", "Exp", 24),
                                                            new StatTriplet("Mighty Belt", "Pick", 7),
                                                            new StatTriplet("Mighty Belt", "LvlRe", 16),
                                                            new StatTriplet("Spirit Stone", "MF", 18),
                                                            new StatTriplet("Spirit Stone", "GF", 20),
                                                            new StatTriplet("Spirit Stone", "Exp", 24),
                                                            new StatTriplet("Spirit Stone", "Pick", 7),
                                                            new StatTriplet("Spirit Stone", "LvlRe", 16),
                                                            new StatTriplet("Spirit Stone", "Soc", 1),
                                                            new StatTriplet("Voodoo Mask", "MF", 18),
                                                            new StatTriplet("Voodoo Mask", "GF", 20),
                                                            new StatTriplet("Voodoo Mask", "Exp", 24),
                                                            new StatTriplet("Voodoo Mask", "Pick", 7),
                                                            new StatTriplet("Voodoo Mask", "LvlRe", 16),
                                                            new StatTriplet("Voodoo Mask", "Soc", 1),
                                                            new StatTriplet("Wizard Hat", "MF", 18),
                                                            new StatTriplet("Wizard Hat", "GF", 20),
                                                            new StatTriplet("Wizard Hat", "Exp", 24),
                                                            new StatTriplet("Wizard Hat", "Pick", 7),
                                                            new StatTriplet("Wizard Hat", "LvlRe", 16),
                                                            new StatTriplet("Wizard Hat", "Soc", 1),
                                                            new StatTriplet("Weapon", "Dmg%", 50),
                                                            new StatTriplet("Weapon", "CritD", 100),
                                                            new StatTriplet("Weapon", "AtkSpd", 11),
                                                            new StatTriplet("Weapon", "ArcD", 667),
                                                            new StatTriplet("Weapon", "FireD", 667),
                                                            new StatTriplet("Weapon", "HolyD", 667),
                                                            new StatTriplet("Weapon", "PoisonD", 667),
                                                            new StatTriplet("Weapon", "LtnD", 667),
                                                            new StatTriplet("Weapon", "ColdD", 399),
                                                            new StatTriplet("Off-Hand", "Crit", 8.5),
                                                            new StatTriplet("Off-Hand", "AtkSpd", 15),
                                                            new StatTriplet("Shield", "Crit", 10),
                                                            new StatTriplet("Ring", "Crit", 4.5),
                                                            new StatTriplet("Ring", "CritD", 35),
                                                            new StatTriplet("Ring", "AtkSpd", 9),
                                                            new StatTriplet("Ring", "MinD", 27),
                                                            new StatTriplet("Ring", "MaxD", 27),
                                                            new StatTriplet("Amulet", "Crit", 8.5),
                                                            new StatTriplet("Amulet", "CritD", 65),
                                                            new StatTriplet("Amulet", "AtkSpd", 9),
                                                            new StatTriplet("Amulet", "MinD", 27),
                                                            new StatTriplet("Amulet", "MaxD", 27),
                                                            new StatTriplet("Helm", "Crit", 6),
                                                            new StatTriplet("Gloves", "Crit", 10),
                                                            new StatTriplet("Gloves", "CritD", 50),
                                                            new StatTriplet("Gloves", "AtkSpd", 9),
                                                            new StatTriplet("Bracers", "Crit", 6),
                                                            new StatTriplet("Spirit Stone", "Crit", 4.5),
                                                            new StatTriplet("Voodoo Mask", "Crit", 4.5),
                                                            new StatTriplet("Wizard Hat", "Crit", 4.5),
                                                            new StatTriplet("Off-Hand", "Thorn", 979),
                                                            new StatTriplet("Shield", "Armor", 397),
                                                            new StatTriplet("Shield", "Block", 9),
                                                            new StatTriplet("Shield", "RDMelee", 6),
                                                            new StatTriplet("Shield", "RDRanged", 6),
                                                            new StatTriplet("Shield", "RDElite", 7),
                                                            new StatTriplet("Shield", "Thorn", 2544),
                                                            new StatTriplet("Shield", "ReCC", 14),
                                                            new StatTriplet("Ring", "Armor", 240),
                                                            new StatTriplet("Ring", "Thorn", 979),
                                                            new StatTriplet("Ring", "ReCC", 14),
                                                            new StatTriplet("Amulet", "Armor", 360),
                                                            new StatTriplet("Amulet", "RDMelee", 4),
                                                            new StatTriplet("Amulet", "RDRanged", 4),
                                                            new StatTriplet("Amulet", "Thorn", 1712),
                                                            new StatTriplet("Amulet", "ReCC", 14),
                                                            new StatTriplet("Shoulders", "Armor", 265),
                                                            new StatTriplet("Shoulders", "Thorn", 2544),
                                                            new StatTriplet("Helm", "Armor", 397),
                                                            new StatTriplet("Helm", "Thorn", 1454),
                                                            new StatTriplet("Helm", "ReCC", 14),
                                                            new StatTriplet("Pants", "Armor", 397),
                                                            new StatTriplet("Pants", "Thorn", 1454),
                                                            new StatTriplet("Gloves", "Armor", 265),
                                                            new StatTriplet("Gloves", "Thorn", 1454),
                                                            new StatTriplet("Chest Armor", "Armor", 397),
                                                            new StatTriplet("Chest Armor", "RDMelee", 6),
                                                            new StatTriplet("Chest Armor", "RDRanged", 6),
                                                            new StatTriplet("Chest Armor", "RDElite", 7),
                                                            new StatTriplet("Chest Armor", "Thorn", 2544),
                                                            new StatTriplet("Bracers", "Armor", 265),
                                                            new StatTriplet("Bracers", "RDMelee", 6),
                                                            new StatTriplet("Bracers", "RDRanged", 6),
                                                            new StatTriplet("Bracers", "Thorn", 1454),
                                                            new StatTriplet("Boots", "Armor", 265),
                                                            new StatTriplet("Boots", "Thorn", 1454),
                                                            new StatTriplet("Belt", "Armor", 265),
                                                            new StatTriplet("Belt", "Thorn", 2544),
                                                            new StatTriplet("Cloak", "Armor", 397),
                                                            new StatTriplet("Cloak", "RDRanged", 6),
                                                            new StatTriplet("Cloak", "Thorn", 2544),
                                                            new StatTriplet("Mighty Belt", "Armor", 265),
                                                            new StatTriplet("Mighty Belt", "Thorn", 2544),
                                                            new StatTriplet("Spirit Stone", "Armor", 397),
                                                            new StatTriplet("Spirit Stone", "Thorn", 1454),
                                                            new StatTriplet("Spirit Stone", "ReCC", 14),
                                                            new StatTriplet("Voodoo Mask", "Armor", 397),
                                                            new StatTriplet("Voodoo Mask", "Thorn", 1454),
                                                            new StatTriplet("Voodoo Mask", "ReCC", 14),
                                                            new StatTriplet("Wizard Hat", "Armor", 397),
                                                            new StatTriplet("Wizard Hat", "Thorn", 1454),
                                                            new StatTriplet("Wizard Hat", "ReCC", 14),
                                                            new StatTriplet("Shield", "AR", 80),
                                                            new StatTriplet("Shield", "PhyR", 60),
                                                            new StatTriplet("Shield", "ColdR", 60),
                                                            new StatTriplet("Shield", "FireR", 60),
                                                            new StatTriplet("Shield", "LtnR", 60),
                                                            new StatTriplet("Shield", "PoisonR", 60),
                                                            new StatTriplet("Shield", "ArcR", 60),
                                                            new StatTriplet("Ring", "AR", 70),
                                                            new StatTriplet("Ring", "PhyR", 50),
                                                            new StatTriplet("Ring", "ColdR", 50),
                                                            new StatTriplet("Ring", "FireR", 50),
                                                            new StatTriplet("Ring", "LtnR", 50),
                                                            new StatTriplet("Ring", "PoisonR", 50),
                                                            new StatTriplet("Ring", "ArcR", 50),
                                                            new StatTriplet("Amulet", "AR", 70),
                                                            new StatTriplet("Amulet", "PhyR", 50),
                                                            new StatTriplet("Amulet", "ColdR", 50),
                                                            new StatTriplet("Amulet", "FireR", 50),
                                                            new StatTriplet("Amulet", "LtnR", 50),
                                                            new StatTriplet("Amulet", "PoisonR", 50),
                                                            new StatTriplet("Amulet", "ArcR", 50),
                                                            new StatTriplet("Shoulders", "AR", 80),
                                                            new StatTriplet("Shoulders", "PhyR", 60),
                                                            new StatTriplet("Shoulders", "ColdR", 60),
                                                            new StatTriplet("Shoulders", "FireR", 60),
                                                            new StatTriplet("Shoulders", "LtnR", 60),
                                                            new StatTriplet("Shoulders", "PoisonR", 60),
                                                            new StatTriplet("Shoulders", "ArcR", 60),
                                                            new StatTriplet("Helm", "AR", 80),
                                                            new StatTriplet("Helm", "PhyR", 60),
                                                            new StatTriplet("Helm", "ColdR", 60),
                                                            new StatTriplet("Helm", "FireR", 60),
                                                            new StatTriplet("Helm", "LtnR", 60),
                                                            new StatTriplet("Helm", "PoisonR", 60),
                                                            new StatTriplet("Helm", "ArcR", 60),
                                                            new StatTriplet("Pants", "AR", 80),
                                                            new StatTriplet("Pants", "PhyR", 60),
                                                            new StatTriplet("Pants", "ColdR", 60),
                                                            new StatTriplet("Pants", "FireR", 60),
                                                            new StatTriplet("Pants", "LtnR", 60),
                                                            new StatTriplet("Pants", "PoisonR", 60),
                                                            new StatTriplet("Pants", "ArcR", 60),
                                                            new StatTriplet("Gloves", "AR", 80),
                                                            new StatTriplet("Gloves", "PhyR", 60),
                                                            new StatTriplet("Gloves", "ColdR", 60),
                                                            new StatTriplet("Gloves", "FireR", 60),
                                                            new StatTriplet("Gloves", "LtnR", 60),
                                                            new StatTriplet("Gloves", "PoisonR", 60),
                                                            new StatTriplet("Gloves", "ArcR", 60),
                                                            new StatTriplet("Chest Armor", "AR", 80),
                                                            new StatTriplet("Chest Armor", "PhyR", 60),
                                                            new StatTriplet("Chest Armor", "ColdR", 60),
                                                            new StatTriplet("Chest Armor", "FireR", 60),
                                                            new StatTriplet("Chest Armor", "LtnR", 60),
                                                            new StatTriplet("Chest Armor", "PoisonR", 60),
                                                            new StatTriplet("Chest Armor", "ArcR", 60),
                                                            new StatTriplet("Bracers", "AR", 80),
                                                            new StatTriplet("Bracers", "PhyR", 60),
                                                            new StatTriplet("Bracers", "ColdR", 60),
                                                            new StatTriplet("Bracers", "FireR", 60),
                                                            new StatTriplet("Bracers", "LtnR", 60),
                                                            new StatTriplet("Bracers", "PoisonR", 60),
                                                            new StatTriplet("Bracers", "ArcR", 60),
                                                            new StatTriplet("Boots", "AR", 80),
                                                            new StatTriplet("Boots", "PhyR", 60),
                                                            new StatTriplet("Boots", "ColdR", 60),
                                                            new StatTriplet("Boots", "FireR", 60),
                                                            new StatTriplet("Boots", "LtnR", 60),
                                                            new StatTriplet("Boots", "PoisonR", 60),
                                                            new StatTriplet("Boots", "ArcR", 60),
                                                            new StatTriplet("Belt", "AR", 80),
                                                            new StatTriplet("Belt", "PhyR", 60),
                                                            new StatTriplet("Belt", "ColdR", 60),
                                                            new StatTriplet("Belt", "FireR", 60),
                                                            new StatTriplet("Belt", "LtnR", 60),
                                                            new StatTriplet("Belt", "PoisonR", 60),
                                                            new StatTriplet("Belt", "ArcR", 60),
                                                            new StatTriplet("Cloak", "AR", 70),
                                                            new StatTriplet("Cloak", "PhyR", 50),
                                                            new StatTriplet("Cloak", "ColdR", 50),
                                                            new StatTriplet("Cloak", "FireR", 50),
                                                            new StatTriplet("Cloak", "LtnR", 50),
                                                            new StatTriplet("Cloak", "PoisonR", 50),
                                                            new StatTriplet("Cloak", "ArcR", 50),
                                                            new StatTriplet("Mighty Belt", "AR", 70),
                                                            new StatTriplet("Mighty Belt", "PhyR", 50),
                                                            new StatTriplet("Mighty Belt", "ColdR", 50),
                                                            new StatTriplet("Mighty Belt", "FireR", 50),
                                                            new StatTriplet("Mighty Belt", "LtnR", 50),
                                                            new StatTriplet("Mighty Belt", "PoisonR", 50),
                                                            new StatTriplet("Mighty Belt", "ArcR", 50),
                                                            new StatTriplet("Spirit Stone", "AR", 70),
                                                            new StatTriplet("Spirit Stone", "PhyR", 50),
                                                            new StatTriplet("Spirit Stone", "ColdR", 50),
                                                            new StatTriplet("Spirit Stone", "FireR", 50),
                                                            new StatTriplet("Spirit Stone", "LtnR", 50),
                                                            new StatTriplet("Spirit Stone", "PoisonR", 50),
                                                            new StatTriplet("Spirit Stone", "ArcR", 50),
                                                            new StatTriplet("Voodoo Mask", "AR", 70),
                                                            new StatTriplet("Voodoo Mask", "PhyR", 50),
                                                            new StatTriplet("Voodoo Mask", "ColdR", 50),
                                                            new StatTriplet("Voodoo Mask", "FireR", 50),
                                                            new StatTriplet("Voodoo Mask", "LtnR", 50),
                                                            new StatTriplet("Voodoo Mask", "PoisonR", 50),
                                                            new StatTriplet("Voodoo Mask", "ArcR", 50),
                                                            new StatTriplet("Wizard Hat", "AR", 70),
                                                            new StatTriplet("Wizard Hat", "PhyR", 50),
                                                            new StatTriplet("Wizard Hat", "ColdR", 50),
                                                            new StatTriplet("Wizard Hat", "FireR", 50),
                                                            new StatTriplet("Wizard Hat", "LtnR", 50),
                                                            new StatTriplet("Wizard Hat", "PoisonR", 50),
                                                            new StatTriplet("Wizard Hat", "ArcR", 50),
                                                            new StatTriplet("Weapon", "Stun", 2.6),
                                                            new StatTriplet("Weapon", "Knockback", 2.6),
                                                            new StatTriplet("Weapon", "Slow", 2.6),
                                                            new StatTriplet("Weapon", "Immobilize", 2.6),
                                                            new StatTriplet("Weapon", "Freeze", 2.6),
                                                            new StatTriplet("Weapon", "Fear", 2.6),
                                                            new StatTriplet("Weapon", "Chill", 2.6),
                                                            new StatTriplet("Weapon", "Blind", 2.6),
                                                            new StatTriplet("Off-Hand", "Stun", 2.6),
                                                            new StatTriplet("Off-Hand", "Knockback", 2.6),
                                                            new StatTriplet("Off-Hand", "Slow", 2.6),
                                                            new StatTriplet("Off-Hand", "Immobilize", 2.6),
                                                            new StatTriplet("Off-Hand", "Freeze", 2.6),
                                                            new StatTriplet("Off-Hand", "Fear", 2.6),
                                                            new StatTriplet("Off-Hand", "Chill", 2.6),
                                                            new StatTriplet("Off-Hand", "Blind", 2.6),
                                                            new StatTriplet("Shield", "Stun", 2.6),
                                                            new StatTriplet("Shield", "Knockback", 2.6),
                                                            new StatTriplet("Shield", "Slow", 2.6),
                                                            new StatTriplet("Shield", "Immobilize", 2.6),
                                                            new StatTriplet("Shield", "Freeze", 2.6),
                                                            new StatTriplet("Shield", "Fear", 2.6),
                                                            new StatTriplet("Shield", "Chill", 2.6),
                                                            new StatTriplet("Shield", "Blind", 2.6),
                                                            new StatTriplet("Amulet", "Blind", 5.1),
                                                            new StatTriplet("Shoulders", "Chill", 5.1),
                                                            new StatTriplet("Helm", "Fear", 5.1),
                                                            new StatTriplet("Pants", "Slow", 5.1),
                                                            new StatTriplet("Gloves", "Stun", 5.1),
                                                            new StatTriplet("Bracers", "Knockback", 5.1),
                                                            new StatTriplet("Boots", "Immobilize", 5.1),
                                                            new StatTriplet("Belt", "Freeze", 5.1),
                                                            new StatTriplet("Mighty Belt", "Freeze", 5.1),
                                                            new StatTriplet("Spirit Stone", "Fear", 5.1),
                                                            new StatTriplet("Voodoo Mask", "Fear", 5.1),
                                                            new StatTriplet("Wizard Hat", "Chill", 5.1),
                                                            new StatTriplet("Weapon", "SpiritRegen", 2.5),
                                                            new StatTriplet("Weapon", "HateRegen", 1.33),
                                                            new StatTriplet("Weapon", "ManaRegen", 14),
                                                            new StatTriplet("Weapon", "MaxArcP", 15),
                                                            new StatTriplet("Weapon", "MaxDisc", 10),
                                                            new StatTriplet("Weapon", "MaxMana", 150),
                                                            new StatTriplet("Weapon", "MaxFury", 15),
                                                            new StatTriplet("Weapon", "ArcPCrit", 10),
                                                            new StatTriplet("Off-Hand", "HateRegen", 1.17),
                                                            new StatTriplet("Off-Hand", "ManaRegen", 11),
                                                            new StatTriplet("Off-Hand", "MaxArcP", 15),
                                                            new StatTriplet("Off-Hand", "MaxDisc", 10),
                                                            new StatTriplet("Off-Hand", "MaxMana", 119),
                                                            new StatTriplet("Off-Hand", "ArcPCrit", 10),
                                                            new StatTriplet("Cloak", "HateRegen", 1.17),
                                                            new StatTriplet("Cloak", "MaxDisc", 10),
                                                            new StatTriplet("Mighty Belt", "MaxFury", 15),
                                                            new StatTriplet("Spirit Stone", "SpiritRegen", 2.5),
                                                            new StatTriplet("Voodoo Mask", "ManaRegen", 11),
                                                            new StatTriplet("Voodoo Mask", "MaxMana", 119),
                                                            new StatTriplet("Wizard Hat", "MaxArcP", 15),
                                                            new StatTriplet("Wizard Hat", "ArcPCrit", 10)
                                                       };

    }
}
